---
title: Age Co partner guidelines
timezone: UTC
collections:
  guidelines:
    title: Guidelines
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: guidelines
  values:
    layout: guideline
permalink: pretty
